#!/bin/bash
# Abo Linux Utility: Low-level package manager (Abo Package .afp).

OPERATION="$1"
PACKAGE_FILE="$2"
ROOTFS_PATH="$3"

if [ -z "$OPERATION" ] || [ -z "$ROOTFS_PATH" ]; then
    echo "Usage: apka [install|query] <package.afp> <rootFS_path>" >&2
    exit 1
fi

install_package() {
    echo "[APKA] Installing $PACKAGE_FILE to $ROOTFS_PATH..."
    if [ -f "$PACKAGE_FILE" ]; then
        tar -xf "$PACKAGE_FILE" -C "$ROOTFS_PATH" || return 1
        echo "[APKA] Package installed successfully."
        echo "$(basename "$PACKAGE_FILE")" >> "$ROOTFS_PATH/var/lib/apka/installed_list"
        return 0
    else
        echo "[APKA] Error: Package file $PACKAGE_FILE not found." >&2
        return 1
    fi
};

case "$OPERATION" in
    "install")
        install_package
        ;;
    "query")
        grep "$(basename "$PACKAGE_FILE")" "$ROOTFS_PATH/var/lib/apka/installed_list"
        ;;
    *)
        echo "[APKA] Error: Unknown operation $OPERATION" >&2
        exit 1
        ;;
esac
