#!/bin/bash
# Abo Linux Utility: Creates the essential File Hierarchy Standard (FHS) directories.
LFS=""
if [ -z "" ]; then
    echo "Error: LFS (rootFS path) not provided." >&2; exit 1
fi
echo "[MKFHS] Creating basic FHS structure in "
mkdir -v /{etc,var,boot,home,mnt,opt,srv,tmp,usr,usr/bin,usr/lib,usr/sbin}
mkdir -v /{bin,lib,sbin}
mkdir -v /var/lib
mkdir -v /var/lib/apka # Abo Package Manager database
mkdir -v /var/{log,mail,spool}
mkdir -v /usr/local/{bin,etc,lib,sbin,share}
mkdir -v /run
echo "FHS structure created successfully."
