#!/bin/bash
# Abo Linux Utility: Creates the essential File Hierarchy Standard (FHS) directories.
LFS="$1"
if [ -z "$LFS" ]; then
    echo "[MKFHS ERROR] Path to LFS (rootFS) is empty or missing." >&2; exit 1
fi
echo "[MKFHS] Creating basic FHS structure in $LFS"
mkdir -v $LFS/{etc,var,boot,home,mnt,opt,srv,tmp,usr,usr/bin,usr/lib,usr/sbin}
mkdir -v $LFS/{bin,lib,sbin}
mkdir -v $LFS/var/lib
mkdir -v $LFS/var/lib/apka # Abo Package Manager database
mkdir -v $LFS/var/{log,mail,spool}
mkdir -v $LFS/usr/local/{bin,etc,lib,sbin,share}
mkdir -v $LFS/run
echo "[MKFHS] FHS structure created successfully."
